project_id = "hsybhjjtxdwtpfvcmoqk"

[functions.search-suppliers]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.stock-sync]
verify_jwt = false

[functions.generate-totp-secret]
verify_jwt = true

[functions.verify-totp]
verify_jwt = true

[functions.enable-totp]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-analytics]
verify_jwt = true

[functions.track-visit]
verify_jwt = false

[functions.delete-users-batch]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false
